### ISSUE TITLE
invalid json output

### ISSUE THREAD

**Issue by deanOcoin** [0x251/gobrute#1]
when writing to balance_check.json a comma needs to added to separate the wallet structures
![image](https://github.com/user-attachments/assets/0f245a3e-a3c5-40a6-9574-a2d5e7c8428f)

**Comment by 0x251** [comment]
Correct, you are using 1.0.0 i suggest using 1.0.1 as it filters received 5460 (which was a 2015 bot) that would transfer 5 dollars to a bunch of common password wallets, to make it look active as a false positive.

You can use 1.0.1 by cloning this repo and running go build . 

As for the json structure, in 1.0.1 it should write as {} without brackets.
